create table `users`
(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,

nom VARCHAR(100) NOT NULL,

prenom VARCHAR(100) NOT NULL,

email VARCHAR(255) NOT NULL UNIQUE,

password VARCHAR(255) NOT NULL,

avatar VARCHAR(255) NOT NULL

);


create table `posts`
(

id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
         
userId INTEGER NOT NULL,
           
message VARCHAR(255) NOT NULL,
        
media VARCHAR(255) NOT NULL,

date VARCHAR(255) NOT NULL

);
